---

- name: Test Connection to my servres
  hosts: nginx_servers
  become: yes

  tasks:
  - name: Install nginx on all servers
    apt: name=nginx state=latest

  - name: Change web site
    ansible.builtin.copy:
      src: ../web/index.nginx-debian.html
      dest: /var/www/html/index.nginx-debian.html
      owner: user
      group: user
      mode: '0644'
