---

- name: Install zabbix
  hosts: zabbix_server
  become: yes

  tasks:
  - name: apt update
    shell: "sudo apt-get update"

  - name: Install nginx on all servers
    apt: name=nginx state=latest

  - name: Install gnupg, apt-transport-https
    apt:
      name:
      - apt-transport-https
      - gnupg
      state: present

  - name: zabbix release
    ansible.builtin.get_url:
      url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
      dest: /home/user/

  - name: install zabbix release
    shell: "dpkg -i zabbix-release_6.4-1+ubuntu22.04_all.deb"

#  - name: Update apt
 #   become: true
  #  apt:
   #   upgrade: yes

  - name: install zabbix server, web, psql
    apt:
      name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.1-pgsql
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent
      - postgresql
