---

- name: Install elasticsearc 
  hosts: elastic_server
  become: yes

  tasks:

  - name: apt update
    shell: "sudo apt-get update"


  - name: Install gnupg, apt-transport-https
    apt:
      name:
      - apt-transport-https
      - gnupg
      state: present

  - name: Get elasticsearch 7.4.1
    ansible.builtin.get_url:
      url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.4.1-amd64.deb
      dest: /home/user/

  - name: Install elasticsearch
    apt:
      deb: /home/user/elasticsearch-7.4.1-amd64.deb

  - name: Systemctl daemon reload
    systemd:
      daemon_reload: true
      name: elasticsearch.service
      state: started

  - name: Copy config file for elasticsearch
    copy:
      src: ../elk/elasticsearch.yml
      dest: /etc/elasticsearch
      mode: 0660
      owner: root
      group: elasticsearch

  - name: Systemctl enable elasticsearch
    systemd:
      name: elasticsearch.service
      state: restarted
