---

- name: Install  kibana
  hosts: kibana_server
  become: yes

  tasks:

  - name: apt update
    shell: "sudo apt-get update"

  - name: Install gnupg, apt-transport-https
    apt:
      name:
      - apt-transport-https
      - gnupg
      state: present

  - name: Get kibana.7.4.1
    ansible.builtin.get_url:
      url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.4.1-amd64.deb
      dest: /home/user/

  - name: Install kibana
    apt:
      deb: /home/user/kibana-7.4.1-amd64.deb

  - name: Systemctl daemon reload
    systemd:
      daemon_reload: true
      name: kibana.service
      state: started

  - name: Copy config file for kibana
    copy:
      src: ../elk/kibana.yml
      dest: /etc/kibana
      mode: 0644
      owner: root
      group:

  - name: Systemctl enable  kibana
    systemd:
      name: kibana.service
      state: restarted
